#!/bin/bash

set -Eeuo pipefail
cleanup() {
  logsCleanup
}


logsHelp() {
  cat <<EOF
Command Usage: fedoratricks logs [options]

Options:
-h|--help     Print the help text and exit.
-a|--all      Save dmesg as well as journal current and last boot.
-0|--current  Save the current boot logs (default)
-1|--lastboot Save the previous boot logs.
-d|--dmesg    Save the dmesg output.
-f|--file     File path where to save the logs. Default ~/Downloads/
EOF
}

# Always define option defaults:
current=true
lastboot=false
dmesg=false
datetime=$(date '+%Y-%m-%d_%H-%M-%S');
if [[ -d ${HOME}/Downloads ]]; then
  path="${HOME}/Downloads"
else
  path="${HOME}"
fi

logsExecute() {
  while [[ $# -gt 0 ]]; do
    case $1 in
      -f|--file)
        path="$2"
        shift 2
        ;;
      -a|--all)
        current=true
        lastboot=true
        dmesg=true
        shift
        ;;
      -0|--current)
        current=true
        shift
        ;;
      -1|--lastboot)
        lastboot=true
        shift
        ;;
      -d|--dmesg)
        dmesg=true
        shift
        ;;
      *)
        echo "Unknown option $1"
        exit 1
        ;;
    esac
  done

  # DO STUFF
  if [[ ${dmesg} == true ]]; then
    sudo dmesg -H &> ${path}/dmesg_${datetime}.log
  fi
  if [[ ${current} == true ]] ; then
    journalctl -b 0 &> ${path}/current_${datetime}.log
  fi
  if [[ ${lastboot} == true ]] ; then
    journalctl -b -1 &> ${path}/lastboot_${datetime}.log
  fi
  echo "Saved support logs to ${path}"
}

logsCleanup() {
  # Triggered automatically in case of an unexpected error.
  echo "Cleaned up after <logs>" # todo - possibly do nothing
  exit 2
}

