#!/bin/bash

set -Eeuo pipefail
cleanup() {
	rpmfusionCleanup
}


rpmfusionHelp() {
	cat <<EOF
Command Usage: fedoratricks rpmfusion [options]

Options:
-h|--help    Print the help text and exit.
enable       Enable the RPMFusion repository.
disable      Disable the RPMFusion repository.
status       View the installation status of the RPMFusion repository.
EOF
}

# Always define option defaults:
executeValue="status"

rpmfusionExecute() {
	echo "Executing RPMFusion"

	while [[ $# -gt 0 ]]; do
		case $1 in
			enable)
				executeValue="enable"
				shift
				;;
			disable)
				executeValue="disable"
				shift
				;;
			status)
				executeValue="status"
				shift
				;;
			*)
				echo "Unknown option $1"
				exit 1
				;;
		esac
	done

  # DO STUFF
	if [[ $executeValue = "enable" ]]; then
		if [[ $(grep rpmfusion-free /etc/dnf/repos.override.d/99-config_manager.repo -c) -gt 0 ]]; then
			enable_soft
		else
			enable_install
		fi
	fi
	if [[ $executeValue = "disable" ]]; then
		disable
	fi
	if [[ $executeValue = "status" ]]; then
		echo "Listing installed RPMFusion repositories:"
		echo "$ sudo dnf repo list | grep rpmfusion"
		if repo_list="$(sudo dnf repo list | grep rpmfusion)"; then
			echo "$repo_list"
		else
			echo "No matches found."
		fi
	fi

}

enable_install() {
	cat <<EOF
$ sudo dnf install \ 
	https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \ 
	https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \ 
	&& \ 
	sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1 && \ 
	sudo dnf update @core && \ 
	sudo dnf install rpmfusion-\*-appstream-data
EOF
	sudo dnf install \
	"https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
	"https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
	sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1
	sudo dnf update @core
	sudo dnf install rpmfusion-\*-appstream-data
}

enable_soft() {
	cat <<EOF
$ sudo dnf config-manager enable \ 
	rpmfusion-free \ 
	rpmfusion-free-updates \ 
	rpmfusion-nonfree \ 
	rpmfusion-nonfree-updates && \ 
	sudo dnf config-manager unsetopt \ 
	fedora-cisco-openh264.enabled
EOF
	sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1
	sudo dnf config-manager enable rpmfusion-{free,nonfree} rpmfusion-{free,nonfree}-updates
}

disable() {
  cat <<EOF
$ sudo dnf config-manager disable \ 
	rpmfusion-free \ 
	rpmfusion-free-updates \ 
	rpmfusion-nonfree \ 
	rpmfusion-nonfree-updates && \ 
	sudo dnf config-manager unsetopt \ 
	fedora-cisco-openh264.enabled
EOF
	sudo dnf config-manager unsetopt fedora-cisco-openh264.enabled
	sudo dnf config-manager disable rpmfusion-{free,nonfree} rpmfusion-{free,nonfree}-updates
}


rpmfusionCleanup() {
	# Triggered automatically in case of an unexpected error.
	echo "Cleaned up after RPMFusion"
	echo "Tried to do $executeValue and failed."
	exit 2
}
