#!/bin/bash

set -Eeuo pipefail
cleanup() {
  templateCleanup
}


templateHelp() {
  cat <<EOF
Command Usage: fedoratricks template [options]

Options:
-h|--help    Print the help text and exit.
-b|--boolean Toggle a flag.
-v|--value   Set a custom value.
EOF
}

# Always define option defaults:
exampleValue="defaultValue"
exampleBool=false

templateExecute() {
  echo "Executing <template>"

  while [[ $# -gt 0 ]]; do
    case $1 in
      -v|--value)
        exampleValue="$2"
        shift 2
        ;;
      -b|--boolean)
        exampleBool=true
        shift
        ;;
      *)
        echo "Unknown option $1"
        exit 1
        ;;
    esac
  done

  # DO STUFF
  echo "-b: ${exampleBool}"
  echo "-v: ${exampleValue}"
}

templateCleanup() {
  # Triggered automatically in case of an unexpected error.
  echo "Cleaned up after <template>"
  exit 2
}

